name: Checks

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install validation tools
        run: sudo apt-get update && sudo apt-get install -y desktop-file-utils appstream
      - name: Set up Python environment
        run: |
          python3 -m venv .venv
          .venv/bin/python -m pip install --editable . -r requirements-dev.txt
      - name: Test and validate
        run: make check
